name: xgb-gpu118
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit=11.8
  - py-xgboost=2.1.1
  - py-xgboost-gpu=2.1.1
  - _py-xgboost-mutex=2.0=gpu_0
  - libxgboost=2.1.1
  - numpy=1.22.3
  - scipy=1.8.1
  - scikit-learn=1.6.1
  - pandas
  - matplotlib
  - ipykernel
  - jupyter
  - pip
  - psutil
  - joblib
  - tornado
  - pyzmq
